### ISSUE TITLE
Cannot recover from PCSCException: SCARD_E_NOT_TRANSACTED

### ISSUE THREAD

**Issue by Nepherte** [e-Contract/commons-eid#12]
If the user removes an eid while reading a file on the card, the stacktrace below occurs. I cannot seem to recover from this state, aside from re-attaching the card reader (which is sometimes not possible). The eid Viewer does not seem to have this problem. I can simply re-insert the card there, which is the behavior I would like here as well. Any thoughts?

I can reproduce on Windows 10 and macOS 10.13.3, with card readers Vasco 870 and ACR38.

Caused by: javax.smartcardio.CardException: sun.security.smartcardio.PCSCException: SCARD_E_NOT_TRANSACTED
	at sun.security.smartcardio.ChannelImpl.doTransmit(ChannelImpl.java:219)
	at sun.security.smartcardio.ChannelImpl.transmit(ChannelImpl.java:90)
	at be.fedict.commons.eid.client.BeIDCard.transmit(BeIDCard.java:1259)
	at be.fedict.commons.eid.client.BeIDCard.transmit(BeIDCard.java:1250)
	at be.fedict.commons.eid.client.BeIDCard.transmitCommand(BeIDCard.java:1231)
	at be.fedict.commons.eid.client.BeIDCard.readBinary(BeIDCard.java:1070)
	at be.fedict.commons.eid.client.BeIDCard.readFile(BeIDCard.java:1146)

**Comment by qxlsz** [comment]
How did you resolve this ?

**Comment by Nepherte** [comment]
I haven't... I recall having tried to refresh/dispose/... cards to no avail. Still hoping to get feedback from the developer (@fcorneli).

**Comment by qxlsz** [comment]
@Nepherte did you try removing pcsc drivers and reinstalling them back ?
